version: 0.2

phases:
  pre_build:
    commands:
      - npm install -g newman
      - npm install -g newman-reporter-htmlextra

  build:
    commands:
      - newman run -r html,cli sample_service.postman_collection --newman-reporter-htmlextra-export report.html
artifacts:
  files:
    - report.html