version: 0.2

phases:
  pre_build:
    commands:
      - npm install -g newman
    ##  - npm install -g newman-reporter-htmlextra
  build:
    commands:
      ##- newman run -r html,cli sample_service.postman_collection --reporter-htmlextra-export report.html
      - npm install newman-reporter-html
      - newman run sample_service.postman_collection -r htmlextra --reporter-htmlextra-export report.html

artifacts:
  files:
    - report.html