version: 0.2
node_js:
  - 17

phases:
  install:
    runtime - versions:
    nodejs: 17
  commands:
    -echo Installing
  pre_build:
    commands:
      #- npm install latest-version@6.0.0
      #- npm install -g newman latest-version@6.0.0
      #- npm install -g js-yaml
      #- npm install -g newman-reporter-htmlextra@1.22.3
      - echo Installing source NPM dependencies. -
        npm install
  build:
    commands:
      - newman run -r htmlextra,cli sample_service.postman_collection --reporter-htmlextra-export report.html
      #- newman run DSS_API_Status_Testing.postman_collection.json -r htmlextra --reporter-htmlextra-export report.html

artifacts:
  files:
    - report.html