version: 0.2

phases:
  install:
    runtime-versions:
      node_js: 16.13.0
  pre_build:
    commands:
      #- npm install -g newman@latest
      - npm install latest-version
      - npm install -g newman-reporter-htmlextra
  build:
    commands:
      ##- newman run -r html,cli sample_service.postman_collection --reporter-htmlextra-export report.html
      - newman run DSS_API_Status_Testing.postman_collection.json -r htmlextra --reporter-htmlextra-export report.html

artifacts:
  files:
    - report.html