version: 0.2

phases:
  pre_build:
    commands:
      - npm install newman --global
  build:
    commands:
      - newman run -r html,cli sample_service.postman_collection --reporter-html-export postman-sample/postmantestresults/report.html

artifacts:
  files:
    - 'postman-sample/postmantestresults/report.html'