version: 0.2
node_js:
  - 17

phases:
  pre_build:
    commands:
      - npm install latest-version
      - npm install -g newman latest-version
      - npm install -g js-yaml
      - npm install -g newman-reporter-htmlextra latest-version
  build:
    commands:
      - newman run -r htmlextra,cli sample_service.postman_collection --reporter-htmlextra-export report.html
      #- newman run DSS_API_Status_Testing.postman_collection.json -r htmlextra --reporter-htmlextra-export report.html

artifacts:
  files:
    - report.html