version: 0.2

phases:
  pre_build:
    commands:
      - npm install newman --global
  build:
    commands:
      - npm install newman-reporter-html
      - newman run -r html,cli sample_service.postman_collection --reporter-html-export report/report.html

artifacts:
  files:
    - report/report.html