version: 0.2

phases:
  pre_build:
    commands:
      - npm install -g newman
  build:
    commands:
      - newman run sample_service.postman_collection -r htmlextra --reporter-htmlextra-export ./report/report.html
artifacts:
  files:
    - ./report/report.html