version: 0.2

phases:
  pre_build:
    commands:
      - npm install -g newman
  build:
    commands:
      - newman run -r html,cli sample_service.postman_collection --reporter-htmlextra-export ./report.html

artifacts:
  files:
    - ./report.html