version: 0.2
node_js:
  - '7'

phases:
  pre_build:
    commands:
      - npm install newman --global
      - npm install -g newman-reporter-htmlextra
  build:
    commands:
      ##- newman run -r html,cli sample_service.postman_collection --reporter-htmlextra-export report.html
      - newman run sample_service.postman_collection -r htmlextra --reporter-htmlextra-export report.html

artifacts:
  files:
    - report.html